from pathlib import Path
import sys, json
import pandas as pd
import numpy as np
PROJECT_ROOT=Path(__file__).resolve().parents[2]
sys.path.append(str(PROJECT_ROOT))
from src.common.utils import *
CONFIG=load_config(); BRONZE=PROJECT_ROOT/CONFIG['bronze_path']; SILVER=PROJECT_ROOT/CONFIG['silver_path']; GOLD=PROJECT_ROOT/CONFIG['gold_path']; QUAR=PROJECT_ROOT/CONFIG['quarantine_path']; REPORT=PROJECT_ROOT/CONFIG['report_path']; META=PROJECT_ROOT/CONFIG['metadata_path']
RAW={
'customers':'data/raw/master/customers.csv','suppliers':'data/raw/master/suppliers.csv','products':'data/raw/master/products.csv','warehouses':'data/raw/master/warehouses.csv','carriers':'data/raw/master/carriers.csv','calendar':'data/raw/reference/calendar.csv','fx_rates':'data/raw/reference/fx_rates.csv','sales_orders':'data/raw/transactions/sales_orders.csv','sales_order_lines':'data/raw/transactions/sales_order_lines.csv','purchase_orders':'data/raw/transactions/purchase_orders.csv','purchase_order_lines':'data/raw/transactions/purchase_order_lines.csv','shipments':'data/raw/transactions/shipments.csv','shipment_events':'data/raw/transactions/shipment_events.csv','receipts':'data/raw/transactions/receipts.csv','receipt_lines':'data/raw/transactions/receipt_lines.csv','inventory_snapshots':'data/raw/transactions/inventory_snapshots.csv','inventory_adjustments':'data/raw/transactions/inventory_adjustments.csv','returns':'data/raw/transactions/returns.csv','invoices':'data/raw/transactions/invoices.csv','payments':'data/raw/transactions/payments.csv','product_cdc':'data/raw/cdc/product_cdc.csv','customer_cdc':'data/raw/cdc/customer_cdc.csv'}
def save(df,path): write_csv(df,path)
def q(name, df, reason):
    out=df.copy(); out['quarantine_reason']=reason
    if len(out)==0: out=pd.DataFrame(columns=['quarantine_reason'])
    save(out, QUAR/f'{name}.csv'); return len(df)
def bronze(name, df):
    out=df.copy(); out['_bronze_loaded_at_utc']=pd.Timestamp.utcnow().isoformat(); out['_source_file']=RAW[name]; save(out, BRONZE/f'{name}.csv')
def c_customers(df):
    d=df.copy(); d['customer_id']=clean_text(d.customer_id,'', 'upper'); d['customer_name']=clean_text(d.customer_name,case='title'); d['customer_segment']=clean_text(d.customer_segment,'Unknown','title'); d['industry']=clean_text(d.industry,case='title'); d['city']=clean_text(d.city,case='title'); d['state']=clean_text(d.state,'Unknown','upper'); d['country']=clean_text(d.country,case='upper').replace({'UNITED STATES':'USA'}); d['region']=clean_text(d.region,'Unknown','title'); d['signup_date']=parse_date(d.signup_date); d['credit_limit']=parse_number(d.credit_limit,0); d['payment_terms']=clean_text(d.payment_terms,'Unknown','upper'); d['risk_tier']=clean_text(d.risk_tier,'Unknown','title'); d['is_active']=bool_from_text(d.is_active); d=d.drop_duplicates(['customer_id']); d['customer_nk_hash']=d.customer_id.map(stable_hash); return d
def c_suppliers(df):
    d=df.copy(); d['supplier_id']=clean_text(d.supplier_id,'','upper'); d['supplier_name']=clean_text(d.supplier_name,case='title'); d['supplier_tier']=clean_text(d.supplier_tier,'Unknown','title'); d['country']=clean_text(d.country,case='upper'); d['lead_time_days']=parse_number(d.lead_time_days); d['quality_score']=parse_number(d.quality_score); d['on_time_delivery_rate']=parse_number(d.on_time_delivery_rate); d['is_active']=bool_from_text(d.is_active); return d.drop_duplicates(['supplier_id'])
def c_products(df):
    d=df.copy(); d['product_id']=clean_text(d.product_id,'','upper'); d['product_name']=clean_text(d.product_name,case='title'); d['category']=clean_text(d.category,case='title'); d['subcategory']=clean_text(d.subcategory,case='title'); d['brand']=clean_text(d.brand,case='title'); d['supplier_id']=clean_text(d.supplier_id,'','upper'); d['standard_cost']=parse_number(d.standard_cost); d['list_price']=parse_number(d.list_price); d['unit_weight_lbs']=parse_number(d.unit_weight_lbs,0); d['hazmat_flag']=bool_from_text(d.hazmat_flag); d['temperature_controlled_flag']=bool_from_text(d.temperature_controlled_flag); d['launch_date']=parse_date(d.launch_date); d['product_status']=clean_text(d.product_status,case='title'); return d.drop_duplicates(['product_id'])
def c_warehouses(df):
    d=df.copy(); d['warehouse_id']=clean_text(d.warehouse_id,'','upper'); d['warehouse_name']=clean_text(d.warehouse_name,case='title'); d['warehouse_type']=clean_text(d.warehouse_type,case='title'); d['city']=clean_text(d.city,case='title'); d['state']=clean_text(d.state,case='upper'); d['country']=clean_text(d.country,case='upper'); d['region']=clean_text(d.region,case='title'); d['capacity_units']=parse_number(d.capacity_units,0); d['open_date']=parse_date(d.open_date); d['is_active']=bool_from_text(d.is_active); return d.drop_duplicates(['warehouse_id'])
def c_carriers(df):
    d=df.copy(); d['carrier_id']=clean_text(d.carrier_id,'','upper'); d['carrier_name']=clean_text(d.carrier_name,case='title'); d['carrier_mode']=clean_text(d.carrier_mode,case='title'); d['service_level']=clean_text(d.service_level,case='title'); d['base_cost_per_mile']=parse_number(d.base_cost_per_mile); d['active_flag']=bool_from_text(d.active_flag); return d.drop_duplicates(['carrier_id'])
def c_calendar(df):
    d=df.copy(); d['calendar_date']=parse_date(d.calendar_date); return d.drop_duplicates(['date_key'])
def c_fx(df):
    d=df.copy(); d['rate_date']=parse_date(d.rate_date); d['currency']=clean_text(d.currency,'USD','upper'); d['usd_rate']=parse_number(d.usd_rate); d['source']=clean_text(d.source,case='lower'); return d.drop_duplicates(['rate_date','currency'], keep='last')
def c_orders(df):
    d=df.copy(); d['order_id']=clean_text(d.order_id,'','upper'); d['customer_id']=clean_text(d.customer_id,'','upper'); d['order_date']=parse_date(d.order_date); d['requested_ship_date']=parse_date(d.requested_ship_date); d['promised_delivery_date']=parse_date(d.promised_delivery_date); d['sales_channel']=clean_text(d.sales_channel,case='title').replace({'Edi':'EDI'}); d['order_status']=clean_text(d.order_status,case='title'); d['order_priority']=clean_text(d.order_priority,case='title'); d['currency']=clean_text(d.currency,'USD','upper'); d['ship_from_warehouse_id']=clean_text(d.ship_from_warehouse_id,'','upper'); d['created_ts']=parse_ts(d.created_ts); d['source_system']=clean_text(d.source_system,case='lower'); d['batch_id']=clean_text(d.batch_id,'UNKNOWN','upper'); return d.drop_duplicates(['order_id'])
def c_lines(df):
    d=df.copy(); d['order_line_id']=clean_text(d.order_line_id,'','upper'); d['order_id']=clean_text(d.order_id,'','upper'); d['line_number']=parse_number(d.line_number,0).astype(int); d['product_id']=clean_text(d.product_id,'','upper'); d['ordered_qty']=parse_number(d.ordered_qty); d['unit_price']=parse_number(d.unit_price); d['discount_pct']=parse_number(d.discount_pct,0); d['line_status']=clean_text(d.line_status,case='title'); d['valid_quantity']=d.ordered_qty.notna()&(d.ordered_qty>0); d['valid_unit_price']=d.unit_price.notna()&(d.unit_price>=0); d['valid_discount']=d.discount_pct.between(0,100); return d.drop_duplicates(['order_line_id'])
def c_po(df):
    d=df.copy(); d['po_id']=clean_text(d.po_id,'','upper'); d['supplier_id']=clean_text(d.supplier_id,'','upper'); d['warehouse_id']=clean_text(d.warehouse_id,'','upper'); d['po_date']=parse_date(d.po_date); d['expected_receipt_date']=parse_date(d.expected_receipt_date); d['po_status']=clean_text(d.po_status,case='title'); d['currency']=clean_text(d.currency,'USD','upper'); d['created_by']=clean_text(d.created_by,'Unknown','lower'); d['source_system']=clean_text(d.source_system,case='lower'); return d.drop_duplicates(['po_id'])
def c_po_lines(df):
    d=df.copy(); d['po_line_id']=clean_text(d.po_line_id,'','upper'); d['po_id']=clean_text(d.po_id,'','upper'); d['line_number']=parse_number(d.line_number,0).astype(int); d['product_id']=clean_text(d.product_id,'','upper'); d['ordered_qty']=parse_number(d.ordered_qty); d['unit_cost']=parse_number(d.unit_cost); d['line_status']=clean_text(d.line_status,case='title'); d['valid_quantity']=d.ordered_qty.notna()&(d.ordered_qty>0); d['valid_unit_cost']=d.unit_cost.notna()&(d.unit_cost>=0); return d.drop_duplicates(['po_line_id'])
def c_ship(df):
    d=df.copy(); d['shipment_id']=clean_text(d.shipment_id,'','upper'); d['order_id']=clean_text(d.order_id,'','upper'); d['warehouse_id']=clean_text(d.warehouse_id,'','upper'); d['carrier_id']=clean_text(d.carrier_id,'','upper'); d['ship_ts']=parse_ts(d.ship_ts); d['delivery_ts']=parse_ts(d.delivery_ts); d['tracking_number']=clean_text(d.tracking_number,'Unknown','upper'); d['shipment_status']=clean_text(d.shipment_status,case='title'); d['shipping_cost']=parse_number(d.shipping_cost,0); d['distance_miles']=parse_number(d.distance_miles); d['promised_delivery_date']=parse_date(d.promised_delivery_date); d['delivery_date']=d.delivery_ts.dt.date.astype('string'); d['ship_date']=d.ship_ts.dt.date.astype('string'); d['transit_days']=(d.delivery_ts-d.ship_ts).dt.total_seconds()/86400; d['is_late_delivery']=pd.to_datetime(d.delivery_date,errors='coerce')>pd.to_datetime(d.promised_delivery_date,errors='coerce'); return d.drop_duplicates(['shipment_id'])
def c_events(df):
    d=df.copy(); d['event_id']=clean_text(d.event_id,'','upper'); d['shipment_id']=clean_text(d.shipment_id,'','upper'); d['event_ts']=parse_ts(d.event_ts); d['event_type']=clean_text(d.event_type,case='title'); d['event_location']=clean_text(d.event_location,case='title'); d['event_notes']=clean_text(d.event_notes,''); return d.drop_duplicates(['event_id'])
def c_receipts(df):
    d=df.copy(); d['receipt_id']=clean_text(d.receipt_id,'','upper'); d['po_id']=clean_text(d.po_id,'','upper'); d['warehouse_id']=clean_text(d.warehouse_id,'','upper'); d['receipt_date']=parse_date(d.receipt_date); d['receipt_status']=clean_text(d.receipt_status,case='title'); d['inspection_status']=clean_text(d.inspection_status,case='title'); d['source_system']=clean_text(d.source_system,case='lower'); return d.drop_duplicates(['receipt_id'])
def c_receipt_lines(df):
    d=df.copy(); d['receipt_line_id']=clean_text(d.receipt_line_id,'','upper'); d['receipt_id']=clean_text(d.receipt_id,'','upper'); d['po_line_id']=clean_text(d.po_line_id,'','upper'); d['product_id']=clean_text(d.product_id,'','upper'); d['received_qty']=parse_number(d.received_qty); d['rejected_qty']=parse_number(d.rejected_qty,0); d['damage_reason']=clean_text(d.damage_reason,''); d['valid_received_qty']=d.received_qty.notna()&(d.received_qty>=0); return d.drop_duplicates(['receipt_line_id'])
def c_inventory(df):
    d=df.copy(); d['snapshot_date']=parse_date(d.snapshot_date); d['warehouse_id']=clean_text(d.warehouse_id,'','upper'); d['product_id']=clean_text(d.product_id,'','upper'); d['on_hand_qty']=parse_number(d.on_hand_qty); d['allocated_qty']=parse_number(d.allocated_qty,0); d['available_qty']=parse_number(d.available_qty); d['reorder_point']=parse_number(d.reorder_point,0); d['safety_stock_qty']=parse_number(d.safety_stock_qty,0); d['inventory_status']=clean_text(d.inventory_status,case='title'); d['valid_inventory_qty']=d.on_hand_qty.notna()&d.available_qty.notna()&(d.on_hand_qty>=0); return d.drop_duplicates(['snapshot_date','warehouse_id','product_id'], keep='last')
def c_adjust(df):
    d=df.copy(); d['adjustment_id']=clean_text(d.adjustment_id,'','upper'); d['warehouse_id']=clean_text(d.warehouse_id,'','upper'); d['product_id']=clean_text(d.product_id,'','upper'); d['adjustment_ts']=parse_ts(d.adjustment_ts); d['adjustment_date']=d.adjustment_ts.dt.date.astype('string'); d['adjustment_qty']=parse_number(d.adjustment_qty); d['adjustment_reason']=clean_text(d.adjustment_reason,case='title'); d['approved_by']=clean_text(d.approved_by,'Unapproved','lower'); d['requires_review']=d.adjustment_qty.abs()>=CONFIG['inventory_adjustment_review_threshold_abs_qty']; return d.drop_duplicates(['adjustment_id'])
def c_returns(df):
    d=df.copy(); d['return_id']=clean_text(d.return_id,'','upper'); d['order_id']=clean_text(d.order_id,'','upper'); d['order_line_id']=clean_text(d.order_line_id,'','upper'); d['product_id']=clean_text(d.product_id,'','upper'); d['return_date']=parse_date(d.return_date); d['return_reason']=clean_text(d.return_reason,case='title'); d['return_qty']=parse_number(d.return_qty); d['refund_amount']=parse_number(d.refund_amount,0); d['return_status']=clean_text(d.return_status,case='title'); return d.drop_duplicates(['return_id'])
def c_invoices(df):
    d=df.copy(); d['invoice_id']=clean_text(d.invoice_id,'','upper'); d['order_id']=clean_text(d.order_id,'','upper'); d['customer_id']=clean_text(d.customer_id,'','upper'); d['invoice_date']=parse_date(d.invoice_date); d['due_date']=parse_date(d.due_date); d['invoice_amount']=parse_number(d.invoice_amount); d['currency']=clean_text(d.currency,'USD','upper'); d['invoice_status']=clean_text(d.invoice_status,case='title'); return d.drop_duplicates(['invoice_id'])
def c_payments(df):
    d=df.copy(); d['payment_id']=clean_text(d.payment_id,'','upper'); d['invoice_id']=clean_text(d.invoice_id,'','upper'); d['payment_date']=parse_date(d.payment_date); d['payment_amount']=parse_number(d.payment_amount); d['payment_method']=clean_text(d.payment_method,case='title').replace({'Ach':'ACH'}); d['payment_status']=clean_text(d.payment_status,case='title'); return d.drop_duplicates(['payment_id'])
def c_product_cdc(df):
    d=df.copy(); d['cdc_id']=clean_text(d.cdc_id,'','upper'); d['product_id']=clean_text(d.product_id,'','upper'); d['effective_ts']=parse_ts(d.effective_ts); d['effective_date']=d.effective_ts.dt.date.astype('string'); d['operation']=clean_text(d.operation,case='upper'); d['new_list_price']=parse_number(d.new_list_price); d['new_product_status']=clean_text(d.new_product_status,case='title'); d['change_reason']=clean_text(d.change_reason,case='lower'); return d.drop_duplicates(['cdc_id'])
def c_customer_cdc(df):
    d=df.copy(); d['cdc_id']=clean_text(d.cdc_id,'','upper'); d['customer_id']=clean_text(d.customer_id,'','upper'); d['effective_ts']=parse_ts(d.effective_ts); d['effective_date']=d.effective_ts.dt.date.astype('string'); d['operation']=clean_text(d.operation,case='upper'); d['new_customer_segment']=clean_text(d.new_customer_segment,case='title'); d['new_risk_tier']=clean_text(d.new_risk_tier,case='title'); d['new_payment_terms']=clean_text(d.new_payment_terms,case='upper'); d['change_reason']=clean_text(d.change_reason,case='lower'); return d.drop_duplicates(['cdc_id'])
CLEAN={'customers':c_customers,'suppliers':c_suppliers,'products':c_products,'warehouses':c_warehouses,'carriers':c_carriers,'calendar':c_calendar,'fx_rates':c_fx,'sales_orders':c_orders,'sales_order_lines':c_lines,'purchase_orders':c_po,'purchase_order_lines':c_po_lines,'shipments':c_ship,'shipment_events':c_events,'receipts':c_receipts,'receipt_lines':c_receipt_lines,'inventory_snapshots':c_inventory,'inventory_adjustments':c_adjust,'returns':c_returns,'invoices':c_invoices,'payments':c_payments,'product_cdc':c_product_cdc,'customer_cdc':c_customer_cdc}

def scd_customer(c,cdc):
    base=c[['customer_id','customer_name','customer_segment','industry','city','state','country','region','signup_date','credit_limit','payment_terms','risk_tier','is_active']].copy(); base['effective_start_date']=base.signup_date.fillna('1900-01-01'); base['record_source']='customer_master'
    upd=cdc.merge(c[['customer_id','customer_name','industry','city','state','country','region','signup_date','credit_limit','is_active']], on='customer_id', how='inner').rename(columns={'new_customer_segment':'customer_segment','new_risk_tier':'risk_tier','new_payment_terms':'payment_terms','effective_date':'effective_start_date','change_reason':'record_source'})[base.columns]
    s=pd.concat([base,upd], ignore_index=True); s['_dt']=pd.to_datetime(s.effective_start_date,errors='coerce'); s=s.sort_values(['customer_id','_dt']); s['effective_end_date']=s.groupby('customer_id')['_dt'].shift(-1).dt.date.astype('string').fillna('9999-12-31'); s['is_current']=s.effective_end_date.eq('9999-12-31'); s['customer_sk']=[stable_hash(a,b,c,d,e) for a,b,c,d,e in zip(s.customer_id,s.effective_start_date,s.customer_segment,s.risk_tier,s.payment_terms)]; return s.drop(columns=['_dt'])[['customer_sk']+[x for x in s.columns if x not in ['customer_sk','_dt']]]
def scd_product(p,cdc):
    base=p.copy(); base['effective_start_date']=base.launch_date.fillna('1900-01-01'); base['record_source']='product_master'
    upd=cdc.merge(p.drop(columns=['list_price','product_status']), on='product_id', how='inner'); upd['list_price']=upd.new_list_price; upd['product_status']=upd.new_product_status; upd['effective_start_date']=upd.effective_date; upd['record_source']=upd.change_reason; upd=upd[base.columns]
    s=pd.concat([base,upd], ignore_index=True); s['_dt']=pd.to_datetime(s.effective_start_date,errors='coerce'); s=s.sort_values(['product_id','_dt']); s['effective_end_date']=s.groupby('product_id')['_dt'].shift(-1).dt.date.astype('string').fillna('9999-12-31'); s['is_current']=s.effective_end_date.eq('9999-12-31'); s['product_sk']=[stable_hash(a,b,c,d) for a,b,c,d in zip(s.product_id,s.effective_start_date,s.list_price,s.product_status)]; return s.drop(columns=['_dt'])
def build_gold(s):
    c=s['customers']; sup=s['suppliers']; p=s['products']; w=s['warehouses']; car=s['carriers']; fx=s['fx_rates']; o=s['sales_orders']; l=s['sales_order_lines']; po=s['purchase_orders']; pol=s['purchase_order_lines']; sh=s['shipments']; rec=s['receipts']; rcl=s['receipt_lines']; inv=s['inventory_snapshots']; adj=s['inventory_adjustments']; ret=s['returns']; invoices=s['invoices']; pay=s['payments']
    for name,df in {'dim_customer_scd2':scd_customer(c,s['customer_cdc']),'dim_product_scd2':scd_product(p,s['product_cdc']),'dim_supplier':sup,'dim_warehouse':w,'dim_carrier':car}.items(): save(df,GOLD/f'{name}.csv')
    orders=o[o.customer_id.isin(c.customer_id)&o.ship_from_warehouse_id.isin(w.warehouse_id)&o.order_date.notna()].copy()
    lines=l[l.order_id.isin(orders.order_id)&l.product_id.isin(p.product_id)&l.valid_quantity&l.valid_unit_price&l.valid_discount].copy(); lines['gross_sales']=lines.ordered_qty*lines.unit_price; lines['discount_amount']=lines.gross_sales*(lines.discount_pct/100); lines['net_sales']=lines.gross_sales-lines.discount_amount
    sales=lines.merge(orders[['order_id','customer_id','order_date','promised_delivery_date','sales_channel','order_status','order_priority','currency','ship_from_warehouse_id']],on='order_id').merge(p[['product_id','category','subcategory','brand','supplier_id','standard_cost','unit_weight_lbs']],on='product_id',how='left')
    sales=sales.merge(fx[['rate_date','currency','usd_rate']], left_on=['order_date','currency'], right_on=['rate_date','currency'], how='left'); missing_fx=sales[sales.usd_rate.isna()]; q('sales_lines_missing_fx_rate',missing_fx,'Sales line currency/date missing FX rate'); sales['usd_rate']=sales.usd_rate.fillna(1); sales['net_sales_usd']=sales.net_sales*sales.usd_rate; sales['gross_sales_usd']=sales.gross_sales*sales.usd_rate; sales['discount_amount_usd']=sales.discount_amount*sales.usd_rate; sales['estimated_cost_usd']=sales.ordered_qty*sales.standard_cost.fillna(0)*sales.usd_rate; sales['gross_margin_usd']=sales.net_sales_usd-sales.estimated_cost_usd; sales['is_large_order_line']=sales.net_sales_usd>=CONFIG['large_order_threshold_usd']; save(sales,GOLD/'fact_sales_order_lines.csv')
    order_fact=sales.groupby('order_id',as_index=False).agg(order_line_count=('order_line_id','count'),total_order_qty=('ordered_qty','sum'),gross_sales_usd=('gross_sales_usd','sum'),net_sales_usd=('net_sales_usd','sum'),discount_amount_usd=('discount_amount_usd','sum'),gross_margin_usd=('gross_margin_usd','sum')).merge(orders,on='order_id',how='left'); save(order_fact,GOLD/'fact_sales_orders.csv')
    ship=sh[sh.order_id.isin(orders.order_id)&sh.carrier_id.isin(car.carrier_id)].merge(orders[['order_id','customer_id','order_date','promised_delivery_date']],on='order_id',how='left'); save(ship,GOLD/'fact_shipments.csv')
    valid_po=po[po.supplier_id.isin(sup.supplier_id)&po.warehouse_id.isin(w.warehouse_id)].copy(); valid_pol=pol[pol.po_id.isin(valid_po.po_id)&pol.product_id.isin(p.product_id)&pol.valid_quantity&pol.valid_unit_cost].copy(); proc=valid_pol.merge(valid_po[['po_id','supplier_id','warehouse_id','po_date','expected_receipt_date','currency','po_status']],on='po_id'); proc['po_line_amount']=proc.ordered_qty*proc.unit_cost; proc=proc.merge(fx[['rate_date','currency','usd_rate']],left_on=['po_date','currency'],right_on=['rate_date','currency'],how='left'); proc['usd_rate']=proc.usd_rate.fillna(1); proc['po_line_amount_usd']=proc.po_line_amount*proc.usd_rate; save(proc,GOLD/'fact_purchase_order_lines.csv')
    receipt=rcl[rcl.po_line_id.isin(valid_pol.po_line_id)&rcl.valid_received_qty].merge(rec[['receipt_id','po_id','warehouse_id','receipt_date','receipt_status','inspection_status']],on='receipt_id',how='left').merge(valid_pol[['po_line_id','po_id','ordered_qty','unit_cost']],on=['po_line_id','po_id'],how='left'); receipt['fill_rate']=safe_divide(receipt.received_qty,receipt.ordered_qty); receipt['rejected_rate']=safe_divide(receipt.rejected_qty,receipt.received_qty); save(receipt,GOLD/'fact_receipts.csv')
    latest=inv.sort_values('snapshot_date').groupby(['warehouse_id','product_id'],as_index=False).tail(1); latest=latest[latest.warehouse_id.isin(w.warehouse_id)&latest.product_id.isin(p.product_id)]; latest['stockout_flag']=latest.available_qty<=0; latest['below_reorder_point_flag']=latest.available_qty<=latest.reorder_point; latest['overstock_flag']=latest.available_qty>latest.reorder_point*4; save(latest,GOLD/'inventory_position_current.csv')
    adjf=adj[adj.warehouse_id.isin(w.warehouse_id)&adj.product_id.isin(p.product_id)&adj.adjustment_qty.notna()]; save(adjf,GOLD/'fact_inventory_adjustments.csv')
    valid_ret=ret[ret.order_id.isin(orders.order_id)&ret.order_line_id.isin(l.order_line_id)]; save(valid_ret,GOLD/'fact_returns.csv')
    valid_inv=invoices[invoices.order_id.isin(orders.order_id)&invoices.invoice_amount.notna()].copy(); valid_pay=pay[pay.invoice_id.isin(valid_inv.invoice_id)&pay.payment_amount.notna()].copy(); paid=valid_pay[valid_pay.payment_status.eq('Posted')].groupby('invoice_id',as_index=False).agg(total_paid=('payment_amount','sum'),last_payment_date=('payment_date','max'),payment_count=('payment_id','count')); ar=valid_inv.merge(paid,on='invoice_id',how='left').fillna({'total_paid':0,'payment_count':0}); ar['open_amount']=ar.invoice_amount-ar.total_paid; ar['paid_in_full_flag']=ar.open_amount.abs()<=.01; ar['days_past_due']=(pd.Timestamp('2026-06-01')-pd.to_datetime(ar.due_date,errors='coerce')).dt.days; ar['is_past_due']=(ar.open_amount>0)&(ar.days_past_due>0); save(ar,GOLD/'accounts_receivable_aging.csv')
    save(sales.groupby(['order_date','sales_channel'],as_index=False).agg(order_count=('order_id','nunique'),line_count=('order_line_id','count'),units_ordered=('ordered_qty','sum'),net_sales_usd=('net_sales_usd','sum'),gross_margin_usd=('gross_margin_usd','sum')),GOLD/'mart_daily_sales.csv')
    prod=sales.groupby(['product_id','category','subcategory','brand'],as_index=False).agg(units_ordered=('ordered_qty','sum'),net_sales_usd=('net_sales_usd','sum'),gross_margin_usd=('gross_margin_usd','sum'),order_count=('order_id','nunique')); rprod=valid_ret.groupby('product_id',as_index=False).agg(returned_qty=('return_qty','sum'),refund_amount=('refund_amount','sum'),return_count=('return_id','count')); prod=prod.merge(rprod,on='product_id',how='left').fillna({'returned_qty':0,'refund_amount':0,'return_count':0}); prod['return_rate']=safe_divide(prod.returned_qty,prod.units_ordered); save(prod.sort_values('net_sales_usd',ascending=False),GOLD/'mart_product_performance.csv')
    supp=proc.groupby('supplier_id',as_index=False).agg(po_count=('po_id','nunique'),ordered_units=('ordered_qty','sum'),po_spend_usd=('po_line_amount_usd','sum')).merge(sup[['supplier_id','supplier_name','supplier_tier','country','quality_score','on_time_delivery_rate']],on='supplier_id',how='left'); sr=receipt.merge(valid_po[['po_id','supplier_id','expected_receipt_date']],on='po_id',how='left'); sr['receipt_late_flag']=pd.to_datetime(sr.receipt_date,errors='coerce')>pd.to_datetime(sr.expected_receipt_date,errors='coerce'); srs=sr.groupby('supplier_id',as_index=False).agg(received_units=('received_qty','sum'),avg_fill_rate=('fill_rate','mean'),late_receipt_count=('receipt_late_flag','sum'),receipt_count=('receipt_id','nunique')); supp=supp.merge(srs,on='supplier_id',how='left').fillna({'received_units':0,'avg_fill_rate':0,'late_receipt_count':0,'receipt_count':0}); supp['computed_on_time_rate']=1-safe_divide(supp.late_receipt_count,supp.receipt_count); save(supp.sort_values(['avg_fill_rate','computed_on_time_rate']),GOLD/'mart_supplier_scorecard.csv')
    wh=latest.groupby('warehouse_id',as_index=False).agg(sku_count=('product_id','nunique'),on_hand_qty=('on_hand_qty','sum'),available_qty=('available_qty','sum'),stockout_sku_count=('stockout_flag','sum'),below_reorder_sku_count=('below_reorder_point_flag','sum'),overstock_sku_count=('overstock_flag','sum')).merge(w[['warehouse_id','warehouse_name','region','capacity_units']],on='warehouse_id',how='left'); shipwh=ship.groupby('warehouse_id',as_index=False).agg(shipment_count=('shipment_id','count'),late_delivery_count=('is_late_delivery','sum'),avg_transit_days=('transit_days','mean'),shipping_cost=('shipping_cost','sum')); wh=wh.merge(shipwh,on='warehouse_id',how='left').fillna({'shipment_count':0,'late_delivery_count':0,'avg_transit_days':0,'shipping_cost':0}); wh['capacity_utilization_estimate']=safe_divide(wh.on_hand_qty,wh.capacity_units); save(wh.sort_values('stockout_sku_count',ascending=False),GOLD/'mart_warehouse_operations.csv')
    fulfill=orders[['order_id','customer_id','order_date','promised_delivery_date','order_priority','sales_channel']].merge(ship.groupby('order_id',as_index=False).agg(first_ship_ts=('ship_ts','min'),last_delivery_ts=('delivery_ts','max'),shipment_count=('shipment_id','count'),any_late_delivery=('is_late_delivery','max')),on='order_id',how='left'); fulfill['order_to_ship_days']=(pd.to_datetime(fulfill.first_ship_ts,errors='coerce')-pd.to_datetime(fulfill.order_date,errors='coerce')).dt.total_seconds()/86400; fulfill['order_to_delivery_days']=(pd.to_datetime(fulfill.last_delivery_ts,errors='coerce')-pd.to_datetime(fulfill.order_date,errors='coerce')).dt.total_seconds()/86400; fulfill['unshipped_flag']=fulfill.first_ship_ts.isna(); save(fulfill,GOLD/'mart_fulfillment_performance.csv')
    cust360=c.merge(order_fact.groupby('customer_id',as_index=False).agg(order_count=('order_id','count'),total_net_sales_usd=('net_sales_usd','sum'),total_margin_usd=('gross_margin_usd','sum')),on='customer_id',how='left').merge(valid_inv.groupby('customer_id',as_index=False).agg(invoice_count=('invoice_id','count'),invoiced_amount=('invoice_amount','sum')),on='customer_id',how='left').fillna({'order_count':0,'total_net_sales_usd':0,'total_margin_usd':0,'invoice_count':0,'invoiced_amount':0}); cust360['credit_utilization_estimate']=safe_divide(cust360.invoiced_amount,cust360.credit_limit); cust360['customer_value_tier']=pd.cut(cust360.total_net_sales_usd,bins=[-1,10000,50000,200000,float('inf')],labels=['Bronze','Silver','Gold','Platinum']).astype('string'); save(cust360.sort_values('total_net_sales_usd',ascending=False),GOLD/'mart_customer_360.csv')
    recon=order_fact[['order_id','net_sales_usd']].merge(valid_inv.groupby('order_id',as_index=False).agg(invoice_amount=('invoice_amount','sum')),on='order_id',how='left').fillna({'invoice_amount':0}); recon['difference']=recon.invoice_amount-recon.net_sales_usd; recon['reconciliation_status']=np.where(recon.difference.abs()<=1,'Matched','Mismatch'); save(recon,GOLD/'recon_sales_vs_invoices.csv')
    pr=valid_pol.groupby('po_line_id',as_index=False).agg(ordered_qty=('ordered_qty','sum')).merge(receipt.groupby('po_line_id',as_index=False).agg(received_qty=('received_qty','sum')),on='po_line_id',how='left').fillna({'received_qty':0}); pr['open_qty']=pr.ordered_qty-pr.received_qty; pr['receipt_status_computed']=np.where(pr.open_qty<=0,'Fully Received',np.where(pr.received_qty>0,'Partially Received','Open')); save(pr,GOLD/'recon_po_vs_receipts.csv')
    for name,df in {'exception_late_deliveries':ship[ship.is_late_delivery.fillna(False)],'exception_low_fill_rate_receipts':receipt[receipt.fill_rate<CONFIG['low_fill_rate_threshold']],'exception_stockouts':latest[latest.stockout_flag],'exception_inventory_adjustments_review':adjf[adjf.requires_review.fillna(False)],'exception_ar_past_due':ar[ar.is_past_due],'exception_sales_invoice_mismatches':recon[recon.reconciliation_status.eq('Mismatch')]}.items(): save(df,GOLD/f'{name}.csv')

def main():
    ensure_dirs(BRONZE,SILVER,GOLD,QUAR,REPORT,META); raw_counts={}; silver={}
    for name,path in RAW.items():
        raw=read_csv(PROJECT_ROOT/path); raw_counts[name]=len(raw); bronze(name,raw); clean=CLEAN[name](raw); silver[name]=clean; save(clean,SILVER/f'{name}.csv')
    qs={}; c=silver
    qs['products_invalid_supplier_id']=q('products_invalid_supplier_id',c['products'][~c['products'].supplier_id.isin(c['suppliers'].supplier_id)],'Product references missing supplier')
    qs['sales_orders_invalid_customer_id']=q('sales_orders_invalid_customer_id',c['sales_orders'][~c['sales_orders'].customer_id.isin(c['customers'].customer_id)],'Sales order references missing customer')
    qs['sales_orders_invalid_warehouse_id']=q('sales_orders_invalid_warehouse_id',c['sales_orders'][~c['sales_orders'].ship_from_warehouse_id.isin(c['warehouses'].warehouse_id)],'Sales order references missing warehouse')
    qs['sales_orders_bad_dates']=q('sales_orders_bad_dates',c['sales_orders'][c['sales_orders'].order_date.isna()|c['sales_orders'].created_ts.isna()],'Sales order has bad dates')
    qs['sales_order_lines_invalid_order_id']=q('sales_order_lines_invalid_order_id',c['sales_order_lines'][~c['sales_order_lines'].order_id.isin(c['sales_orders'].order_id)],'Line references missing order')
    qs['sales_order_lines_invalid_product_id']=q('sales_order_lines_invalid_product_id',c['sales_order_lines'][~c['sales_order_lines'].product_id.isin(c['products'].product_id)],'Line references missing product')
    qs['sales_order_lines_bad_values']=q('sales_order_lines_bad_values',c['sales_order_lines'][~(c['sales_order_lines'].valid_quantity&c['sales_order_lines'].valid_unit_price&c['sales_order_lines'].valid_discount)],'Line has invalid quantity, price, or discount')
    qs['purchase_orders_invalid_supplier_id']=q('purchase_orders_invalid_supplier_id',c['purchase_orders'][~c['purchase_orders'].supplier_id.isin(c['suppliers'].supplier_id)],'PO references missing supplier')
    qs['purchase_orders_invalid_warehouse_id']=q('purchase_orders_invalid_warehouse_id',c['purchase_orders'][~c['purchase_orders'].warehouse_id.isin(c['warehouses'].warehouse_id)],'PO references missing warehouse')
    qs['purchase_order_lines_invalid_po_id']=q('purchase_order_lines_invalid_po_id',c['purchase_order_lines'][~c['purchase_order_lines'].po_id.isin(c['purchase_orders'].po_id)],'PO line references missing PO')
    qs['purchase_order_lines_invalid_product_id']=q('purchase_order_lines_invalid_product_id',c['purchase_order_lines'][~c['purchase_order_lines'].product_id.isin(c['products'].product_id)],'PO line references missing product')
    qs['purchase_order_lines_bad_values']=q('purchase_order_lines_bad_values',c['purchase_order_lines'][~(c['purchase_order_lines'].valid_quantity&c['purchase_order_lines'].valid_unit_cost)],'PO line has invalid values')
    qs['shipments_invalid_order_id']=q('shipments_invalid_order_id',c['shipments'][~c['shipments'].order_id.isin(c['sales_orders'].order_id)],'Shipment references missing order')
    qs['shipments_invalid_carrier_id']=q('shipments_invalid_carrier_id',c['shipments'][~c['shipments'].carrier_id.isin(c['carriers'].carrier_id)],'Shipment references missing carrier')
    qs['shipment_events_invalid_shipment_id']=q('shipment_events_invalid_shipment_id',c['shipment_events'][~c['shipment_events'].shipment_id.isin(c['shipments'].shipment_id)],'Event references missing shipment')
    qs['receipts_invalid_po_id']=q('receipts_invalid_po_id',c['receipts'][~c['receipts'].po_id.isin(c['purchase_orders'].po_id)],'Receipt references missing PO')
    qs['receipt_lines_invalid_receipt_id']=q('receipt_lines_invalid_receipt_id',c['receipt_lines'][~c['receipt_lines'].receipt_id.isin(c['receipts'].receipt_id)],'Receipt line references missing receipt')
    qs['receipt_lines_invalid_po_line_id']=q('receipt_lines_invalid_po_line_id',c['receipt_lines'][~c['receipt_lines'].po_line_id.isin(c['purchase_order_lines'].po_line_id)],'Receipt line references missing PO line')
    qs['receipt_lines_bad_values']=q('receipt_lines_bad_values',c['receipt_lines'][~c['receipt_lines'].valid_received_qty],'Receipt line invalid qty')
    qs['inventory_snapshots_bad_values']=q('inventory_snapshots_bad_values',c['inventory_snapshots'][~c['inventory_snapshots'].valid_inventory_qty],'Inventory bad qty')
    qs['inventory_adjustments_invalid_product_id']=q('inventory_adjustments_invalid_product_id',c['inventory_adjustments'][~c['inventory_adjustments'].product_id.isin(c['products'].product_id)],'Adjustment missing product')
    qs['returns_invalid_order_id']=q('returns_invalid_order_id',c['returns'][~c['returns'].order_id.isin(c['sales_orders'].order_id)],'Return missing order')
    qs['invoices_invalid_order_id']=q('invoices_invalid_order_id',c['invoices'][~c['invoices'].order_id.isin(c['sales_orders'].order_id)],'Invoice missing order')
    qs['payments_invalid_invoice_id']=q('payments_invalid_invoice_id',c['payments'][~c['payments'].invoice_id.isin(c['invoices'].invoice_id)],'Payment missing invoice')
    build_gold(silver)
    dq=[]
    for t,n in raw_counts.items(): dq.append({'check_name':f'{t}_raw_to_silver_row_delta','table_name':t,'raw_count':n,'silver_count':len(silver[t]),'issue_count':n-len(silver[t]),'severity':'info'})
    for k,v in qs.items(): dq.append({'check_name':k,'table_name':k.split('_')[0],'raw_count':'','silver_count':'','issue_count':v,'severity':'warning' if v else 'pass'})
    save(pd.DataFrame(dq),REPORT/'data_quality_report.csv')
    audit=pd.DataFrame([{'pipeline_name':CONFIG['project_name'],'run_timestamp_utc':pd.Timestamp.utcnow().isoformat(),'raw_file_count':len(RAW),'raw_total_rows':sum(raw_counts.values()),'silver_total_rows':sum(len(x) for x in silver.values()),'quarantine_total_rows':sum(qs.values()),'gold_table_count':len(list(GOLD.glob('*.csv'))),'status':'SUCCESS'}]); save(audit,REPORT/'pipeline_audit_log.csv')
    meta={'last_successful_run_utc':pd.Timestamp.utcnow().isoformat(),'sales_orders_created_ts_watermark':str(silver['sales_orders'].created_ts.max()),'shipments_ship_ts_watermark':str(silver['shipments'].ship_ts.max()),'inventory_adjustments_ts_watermark':str(silver['inventory_adjustments'].adjustment_ts.max()),'status':'SUCCESS'}; (META/'run_watermarks.json').write_text(json.dumps(meta,indent=2),encoding='utf-8')
    print('Enterprise supply chain ETL complete.'); print(f'Bronze: {BRONZE}'); print(f'Silver: {SILVER}'); print(f'Quarantine: {QUAR}'); print(f'Gold: {GOLD}')
if __name__=='__main__': main()
