from pathlib import Path
import sys,json,pandas as pd,numpy as np
ROOT=Path(__file__).resolve().parents[2]; sys.path.append(str(ROOT))
from src.common.utils import *
CFG=load_config(); BRONZE=ROOT/CFG['bronze_path']; SILVER=ROOT/CFG['silver_path']; QUAR=ROOT/CFG['quarantine_path']; GOLD=ROOT/CFG['gold_path']; REPORT=ROOT/CFG['report_path']; META=ROOT/CFG['metadata_path']
RAW={p.stem:p for p in (ROOT/'data/raw').rglob('*.csv')}
def save(df,dir_,name): write_csv(df,dir_/f'{name}.csv')
def q(name,df,reason):
    x=df.copy(); x['quarantine_reason']=reason
    if len(x)==0: x=pd.DataFrame(columns=['quarantine_reason'])
    save(x,QUAR,name); return len(df)
def clean_all():
    raw={n:read_csv(p) for n,p in RAW.items()}
    for n,df in raw.items():
        b=df.copy(); b['_bronze_loaded_at_utc']=pd.Timestamp.utcnow().isoformat(); b['_source_file']=str(RAW[n].relative_to(ROOT)); save(b,BRONZE,n)
    s={}
    x=raw['sites'].copy(); x['site_id']=clean_text(x['site_id'],'','upper'); x['site_name']=clean_text(x['site_name'],case='title'); x['site_type']=clean_text(x['site_type'],case='title'); x['city']=clean_text(x['city'],case='title'); x['state']=clean_text(x['state'],case='upper'); x['region']=clean_text(x['region'],case='title'); x['commission_date']=parse_date(x['commission_date']); x['rated_capacity_mw']=parse_number(x['rated_capacity_mw']); x['grid_zone']=clean_text(x['grid_zone'],case='upper'); x['active_flag']=bool_from_text(x['active_flag']); s['sites']=x.drop_duplicates('site_id')
    x=raw['assets'].copy(); x['asset_id']=clean_text(x['asset_id'],'','upper'); x['site_id']=clean_text(x['site_id'],'','upper'); x['asset_type']=clean_text(x['asset_type'],case='title'); x['manufacturer']=clean_text(x['manufacturer'],case='title'); x['install_date']=parse_date(x['install_date']); x['rated_capacity_kw']=parse_number(x['rated_capacity_kw']); x['asset_status']=clean_text(x['asset_status'],case='title'); x['criticality']=clean_text(x['criticality'],case='title'); s['assets']=x.drop_duplicates('asset_id')
    x=raw['customers'].copy(); x['customer_id']=clean_text(x['customer_id'],'','upper'); x['customer_name']=clean_text(x['customer_name'],case='title'); x['segment']=clean_text(x['segment'],'Unknown','title'); x['city']=clean_text(x['city'],case='title'); x['state']=clean_text(x['state'],case='upper'); x['region']=clean_text(x['region'],case='title'); x['signup_date']=parse_date(x['signup_date']); x['credit_class']=clean_text(x['credit_class'],'Unknown','upper'); x['autopay_flag']=bool_from_text(x['autopay_flag']); x['active_flag']=bool_from_text(x['active_flag']); s['customers']=x.drop_duplicates('customer_id')
    x=raw['meters'].copy(); x['meter_id']=clean_text(x['meter_id'],'','upper'); x['customer_id']=clean_text(x['customer_id'],'','upper'); x['site_id']=clean_text(x['site_id'],'','upper'); x['meter_type']=clean_text(x['meter_type'],case='title'); x['install_date']=parse_date(x['install_date']); x['multiplier']=parse_number(x['multiplier']); x['status']=clean_text(x['status'],case='title'); x['firmware_version']=clean_text(x['firmware_version'],'Unknown'); s['meters']=x.drop_duplicates('meter_id')
    x=raw['tariffs'].copy(); x['tariff_id']=clean_text(x['tariff_id'],'','upper'); x['segment']=clean_text(x['segment'],case='title'); x['effective_start_date']=parse_date(x['effective_start_date']); x['effective_end_date']=parse_date(x['effective_end_date']);
    for c in ['energy_rate_per_kwh','demand_rate_per_kw','fixed_monthly_charge']: x[c]=parse_number(x[c],0)
    x['tou_flag']=bool_from_text(x['tou_flag']); s['tariffs']=x.drop_duplicates('tariff_id')
    x=raw['customer_tariffs'].copy(); x['customer_tariff_id']=clean_text(x['customer_tariff_id'],'','upper'); x['customer_id']=clean_text(x['customer_id'],'','upper'); x['tariff_id']=clean_text(x['tariff_id'],'','upper'); x['effective_start_date']=parse_date(x['effective_start_date']); x['effective_end_date']=parse_date(x['effective_end_date']); s['customer_tariffs']=x.drop_duplicates('customer_tariff_id')
    x=raw['meter_readings'].copy(); x['reading_id']=clean_text(x['reading_id'],'','upper'); x['meter_id']=clean_text(x['meter_id'],'','upper'); x['reading_ts']=parse_ts(x['reading_ts']); x['reading_date']=x['reading_ts'].dt.date.astype('string');
    for c in ['kwh','kw_demand','voltage','power_factor']: x[c]=parse_number(x[c])
    x['quality_flag']=clean_text(x['quality_flag'],case='upper'); x['source_system']=clean_text(x['source_system'],case='lower'); x['ingestion_batch_id']=clean_text(x['ingestion_batch_id'],'UNKNOWN','upper'); s['meter_readings']=x.drop_duplicates('reading_id')
    x=raw['asset_telemetry'].copy(); x['telemetry_id']=clean_text(x['telemetry_id'],'','upper'); x['asset_id']=clean_text(x['asset_id'],'','upper'); x['reading_ts']=parse_ts(x['reading_ts']); x['reading_date']=x['reading_ts'].dt.date.astype('string');
    for c in ['power_output_kw','temperature_c','vibration_mm_s','frequency_hz']: x[c]=parse_number(x[c])
    x['status_code']=clean_text(x['status_code'],case='upper'); s['asset_telemetry']=x.drop_duplicates('telemetry_id')
    x=raw['weather_hourly'].copy(); x['site_id']=clean_text(x['site_id'],'','upper'); x['weather_ts']=parse_ts(x['weather_ts']);
    for c in ['temperature_c','wind_speed_mps','solar_irradiance_wm2','humidity_pct']: x[c]=parse_number(x[c])
    x['weather_condition']=clean_text(x['weather_condition'],case='title'); s['weather_hourly']=x.drop_duplicates(['site_id','weather_ts'])
    x=raw['generation_readings'].copy(); x['generation_id']=clean_text(x['generation_id'],'','upper'); x['site_id']=clean_text(x['site_id'],'','upper'); x['reading_ts']=parse_ts(x['reading_ts']); x['reading_date']=x['reading_ts'].dt.date.astype('string');
    for c in ['generation_mw','available_capacity_mw','curtailment_mw']: x[c]=parse_number(x[c])
    s['generation_readings']=x.drop_duplicates('generation_id')
    x=raw['generation_forecast'].copy(); x['forecast_id']=clean_text(x['forecast_id'],'','upper'); x['site_id']=clean_text(x['site_id'],'','upper'); x['forecast_ts']=parse_ts(x['forecast_ts']); x['forecast_generation_mw']=parse_number(x['forecast_generation_mw']); x['model_version']=clean_text(x['model_version']); x['created_ts']=parse_ts(x['created_ts']); s['generation_forecast']=x.drop_duplicates('forecast_id')
    x=raw['outages'].copy(); x['outage_id']=clean_text(x['outage_id'],'','upper'); x['site_id']=clean_text(x['site_id'],'','upper'); x['asset_id']=clean_text(x['asset_id'],'','upper'); x['outage_start_ts']=parse_ts(x['outage_start_ts']); x['outage_end_ts']=parse_ts(x['outage_end_ts']); x['outage_type']=clean_text(x['outage_type'],case='title'); x['cause_code']=clean_text(x['cause_code'],case='title'); x['customers_affected']=parse_number(x['customers_affected'],0); x['estimated_energy_not_served_mwh']=parse_number(x['estimated_energy_not_served_mwh'],0); x['outage_status']=clean_text(x['outage_status'],case='title'); x['duration_hours']=(x['outage_end_ts']-x['outage_start_ts']).dt.total_seconds()/3600; s['outages']=x.drop_duplicates('outage_id')
    x=raw['work_orders'].copy(); x['work_order_id']=clean_text(x['work_order_id'],'','upper'); x['asset_id']=clean_text(x['asset_id'],'','upper'); x['site_id']=clean_text(x['site_id'],'','upper');
    for c in ['created_date','scheduled_date','completed_date']: x[c]=parse_date(x[c])
    x['maintenance_type']=clean_text(x['maintenance_type'],case='title'); x['priority']=clean_text(x['priority'],case='title'); x['status']=clean_text(x['status'],case='title'); x['labor_hours']=parse_number(x['labor_hours']); x['parts_cost']=parse_number(x['parts_cost'],0); s['work_orders']=x.drop_duplicates('work_order_id')
    x=raw['demand_response_events'].copy(); x['event_id']=clean_text(x['event_id'],'','upper'); x['region']=clean_text(x['region'],case='title'); x['event_start_ts']=parse_ts(x['event_start_ts']); x['event_end_ts']=parse_ts(x['event_end_ts']); x['target_reduction_mw']=parse_number(x['target_reduction_mw']); x['actual_reduction_mw']=parse_number(x['actual_reduction_mw']); x['event_status']=clean_text(x['event_status'],case='title'); s['demand_response_events']=x.drop_duplicates('event_id')
    x=raw['bills'].copy(); x['bill_id']=clean_text(x['bill_id'],'','upper'); x['customer_id']=clean_text(x['customer_id'],'','upper');
    for c in ['billing_month','bill_date','due_date']: x[c]=parse_date(x[c])
    for c in ['energy_charge','demand_charge','fixed_charge','tax_amount','total_amount']: x[c]=parse_number(x[c])
    x['bill_status']=clean_text(x['bill_status'],case='title'); s['bills']=x.drop_duplicates('bill_id')
    x=raw['payments'].copy(); x['payment_id']=clean_text(x['payment_id'],'','upper'); x['bill_id']=clean_text(x['bill_id'],'','upper'); x['payment_date']=parse_date(x['payment_date']); x['payment_amount']=parse_number(x['payment_amount']); x['payment_method']=clean_text(x['payment_method'],case='upper'); x['payment_status']=clean_text(x['payment_status'],case='title'); s['payments']=x.drop_duplicates('payment_id')
    x=raw['energy_market_prices'].copy(); x['market_ts']=parse_ts(x['market_ts']); x['grid_zone']=clean_text(x['grid_zone'],case='upper');
    for c in ['day_ahead_price_mwh','real_time_price_mwh','congestion_price_mwh']: x[c]=parse_number(x[c])
    s['energy_market_prices']=x.drop_duplicates(['market_ts','grid_zone'])
    x=raw['calendar'].copy(); x['calendar_date']=parse_date(x['calendar_date']);
    for c in ['year','quarter','month','week_of_year','day_of_week']: x[c]=parse_number(x[c],0).astype(int)
    x['is_weekend']=bool_from_text(x['is_weekend']); s['calendar']=x.drop_duplicates('date_key')
    for n in ['customer_cdc','asset_cdc']:
        x=raw[n].copy(); x['cdc_id']=clean_text(x['cdc_id'],'','upper'); x['effective_ts']=parse_ts(x['effective_ts']); x['operation']=clean_text(x['operation'],case='upper'); x['change_reason']=clean_text(x['change_reason'],case='lower')
        if n=='customer_cdc': x['customer_id']=clean_text(x['customer_id'],'','upper'); x['new_segment']=clean_text(x['new_segment'],case='title'); x['new_credit_class']=clean_text(x['new_credit_class'],case='upper'); x['new_autopay_flag']=bool_from_text(x['new_autopay_flag'])
        else: x['asset_id']=clean_text(x['asset_id'],'','upper'); x['new_asset_status']=clean_text(x['new_asset_status'],case='title'); x['new_criticality']=clean_text(x['new_criticality'],case='title')
        s[n]=x.drop_duplicates('cdc_id')
    for n,df in s.items(): save(df,SILVER,n)
    return raw,s

def scd2_customer(c,cdc):
    base=c[['customer_id','customer_name','segment','city','state','region','signup_date','credit_class','autopay_flag','active_flag']].copy(); base['effective_start_date']=base['signup_date']; base['record_source']='customer_master'
    u=cdc.merge(c[['customer_id','customer_name','city','state','region','signup_date','active_flag']],on='customer_id',how='inner').rename(columns={'new_segment':'segment','new_credit_class':'credit_class','new_autopay_flag':'autopay_flag','change_reason':'record_source'}); u['effective_start_date']=u['effective_ts'].dt.date.astype('string'); u=u[base.columns]
    d=pd.concat([base,u],ignore_index=True); d['_dt']=pd.to_datetime(d['effective_start_date'],errors='coerce'); d=d.sort_values(['customer_id','_dt']); d['effective_end_date']=d.groupby('customer_id')['_dt'].shift(-1).dt.date.astype('string').fillna('9999-12-31'); d['is_current']=d['effective_end_date'].eq('9999-12-31'); d['customer_sk']=[stable_hash(a,b,c1,d1) for a,b,c1,d1 in zip(d['customer_id'],d['effective_start_date'],d['segment'],d['credit_class'])]; return d.drop(columns=['_dt'])
def scd2_asset(a,cdc):
    base=a.copy(); base['effective_start_date']=base['install_date']; base['record_source']='asset_master'
    u=cdc.merge(a.drop(columns=['asset_status','criticality']),on='asset_id',how='inner'); u['asset_status']=u['new_asset_status']; u['criticality']=u['new_criticality']; u['effective_start_date']=u['effective_ts'].dt.date.astype('string'); u['record_source']=u['change_reason']; u=u[base.columns]
    d=pd.concat([base,u],ignore_index=True); d['_dt']=pd.to_datetime(d['effective_start_date'],errors='coerce'); d=d.sort_values(['asset_id','_dt']); d['effective_end_date']=d.groupby('asset_id')['_dt'].shift(-1).dt.date.astype('string').fillna('9999-12-31'); d['is_current']=d['effective_end_date'].eq('9999-12-31'); d['asset_sk']=[stable_hash(a1,b,c1,d1) for a1,b,c1,d1 in zip(d['asset_id'],d['effective_start_date'],d['asset_status'],d['criticality'])]; return d.drop(columns=['_dt'])
def main():
    ensure_dirs(BRONZE,SILVER,QUAR,GOLD,REPORT,META); raw,s=clean_all(); qc={}
    qc['assets_invalid_site_id']=q('assets_invalid_site_id',s['assets'][~s['assets'].site_id.isin(s['sites'].site_id)],'Asset references missing site')
    qc['meters_invalid_customer_id']=q('meters_invalid_customer_id',s['meters'][~s['meters'].customer_id.isin(s['customers'].customer_id)],'Meter references missing customer')
    qc['meters_invalid_site_id']=q('meters_invalid_site_id',s['meters'][~s['meters'].site_id.isin(s['sites'].site_id)],'Meter references missing site')
    mr=s['meter_readings']; qc['meter_readings_invalid_meter_id']=q('meter_readings_invalid_meter_id',mr[~mr.meter_id.isin(s['meters'].meter_id)],'Reading references missing meter'); qc['meter_readings_bad_values']=q('meter_readings_bad_values',mr[mr.reading_ts.isna()|mr.kwh.isna()|(mr.kwh<0)],'Invalid timestamp, kWh, or negative consumption')
    at=s['asset_telemetry']; qc['asset_telemetry_invalid_asset_id']=q('asset_telemetry_invalid_asset_id',at[~at.asset_id.isin(s['assets'].asset_id)],'Telemetry references missing asset'); qc['asset_telemetry_bad_values']=q('asset_telemetry_bad_values',at[at.reading_ts.isna()|at.power_output_kw.isna()],'Invalid timestamp or power output')
    qc['outages_invalid_site_id']=q('outages_invalid_site_id',s['outages'][~s['outages'].site_id.isin(s['sites'].site_id)],'Outage references missing site'); qc['outages_invalid_asset_id']=q('outages_invalid_asset_id',s['outages'][~s['outages'].asset_id.isin(s['assets'].asset_id)],'Outage references missing asset')
    qc['work_orders_invalid_asset_id']=q('work_orders_invalid_asset_id',s['work_orders'][~s['work_orders'].asset_id.isin(s['assets'].asset_id)],'Work order references missing asset'); qc['bills_invalid_customer_id']=q('bills_invalid_customer_id',s['bills'][~s['bills'].customer_id.isin(s['customers'].customer_id)],'Bill references missing customer'); qc['payments_invalid_bill_id']=q('payments_invalid_bill_id',s['payments'][~s['payments'].bill_id.isin(s['bills'].bill_id)],'Payment references missing bill')
    dc=scd2_customer(s['customers'],s['customer_cdc']); da=scd2_asset(s['assets'],s['asset_cdc']); save(dc,GOLD,'dim_customer_scd2'); save(dc[dc.is_current],GOLD,'dim_customer_current'); save(da,GOLD,'dim_asset_scd2'); save(da[da.is_current],GOLD,'dim_asset_current'); save(s['sites'],GOLD,'dim_site'); save(s['meters'],GOLD,'dim_meter'); save(s['tariffs'],GOLD,'dim_tariff')
    valid_mr=mr[mr.meter_id.isin(s['meters'].meter_id)&mr.reading_ts.notna()&mr.kwh.notna()&(mr.kwh>=0)].copy().merge(s['meters'][['meter_id','customer_id','site_id','meter_type','multiplier']],on='meter_id',how='left').merge(s['customers'][['customer_id','segment','region']],on='customer_id',how='left'); valid_mr['adjusted_kwh']=valid_mr.kwh*valid_mr.multiplier.fillna(1); valid_mr['hour']=valid_mr.reading_ts.dt.hour; valid_mr['is_peak_hour']=valid_mr.hour.between(16,21); save(valid_mr,GOLD,'fact_meter_readings')
    daily=valid_mr.groupby(['reading_date','region','segment'],as_index=False).agg(meter_count=('meter_id','nunique'),customer_count=('customer_id','nunique'),consumption_kwh=('adjusted_kwh','sum'),peak_demand_kw=('kw_demand','max'),estimated_reading_count=('quality_flag',lambda x:int((x=='ESTIMATED').sum()))); save(daily,GOLD,'mart_daily_consumption')
    peak=valid_mr.groupby(['reading_date','region','hour'],as_index=False).agg(total_kwh=('adjusted_kwh','sum'),peak_kw=('kw_demand','max')).sort_values(['reading_date','region','peak_kw'],ascending=[True,True,False]).groupby(['reading_date','region'],as_index=False).head(1); save(peak,GOLD,'mart_peak_demand')
    valid_at=at[at.asset_id.isin(s['assets'].asset_id)&at.reading_ts.notna()&at.power_output_kw.notna()].copy().merge(s['assets'][['asset_id','site_id','asset_type','criticality','rated_capacity_kw']],on='asset_id',how='left'); valid_at['temperature_alert']=valid_at.temperature_c>=CFG['telemetry_temperature_alert_c']; valid_at['vibration_alert']=valid_at.vibration_mm_s>=CFG['telemetry_vibration_alert_mm_s']; valid_at['status_alert']=valid_at.status_code.isin(['WARNING','TRIP']); valid_at['anomaly_flag']=valid_at[['temperature_alert','vibration_alert','status_alert']].any(axis=1); save(valid_at,GOLD,'fact_asset_telemetry')
    asset_health=valid_at.groupby(['asset_id','site_id','asset_type','criticality'],as_index=False).agg(reading_count=('telemetry_id','count'),avg_temperature_c=('temperature_c','mean'),max_temperature_c=('temperature_c','max'),avg_vibration_mm_s=('vibration_mm_s','mean'),max_vibration_mm_s=('vibration_mm_s','max'),anomaly_count=('anomaly_flag','sum'),trip_count=('status_code',lambda x:int((x=='TRIP').sum()))); asset_health['anomaly_rate']=safe_divide(asset_health.anomaly_count,asset_health.reading_count); save(asset_health,GOLD,'mart_asset_health')
    gen=s['generation_readings'][s['generation_readings'].site_id.isin(s['sites'].site_id)&s['generation_readings'].reading_ts.notna()].copy().merge(s['sites'][['site_id','site_type','region','rated_capacity_mw','grid_zone']],on='site_id',how='left').merge(s['weather_hourly'],left_on=['site_id','reading_ts'],right_on=['site_id','weather_ts'],how='left'); gen['capacity_factor']=safe_divide(gen.generation_mw.abs(),gen.rated_capacity_mw); gen['net_generation_mw']=gen.generation_mw-gen.curtailment_mw; save(gen,GOLD,'fact_generation_hourly')
    gen_daily=gen.groupby(['reading_date','site_id','site_type','region','grid_zone'],as_index=False).agg(generation_mwh=('generation_mw','sum'),net_generation_mwh=('net_generation_mw','sum'),curtailment_mwh=('curtailment_mw','sum'),avg_capacity_factor=('capacity_factor','mean'),avg_wind_speed_mps=('wind_speed_mps','mean'),avg_solar_irradiance_wm2=('solar_irradiance_wm2','mean')); save(gen_daily,GOLD,'mart_generation_performance')
    fc=s['generation_forecast'].merge(s['generation_readings'][['site_id','reading_ts','generation_mw']],left_on=['site_id','forecast_ts'],right_on=['site_id','reading_ts'],how='inner'); fc['absolute_error_mw']=(fc.forecast_generation_mw-fc.generation_mw).abs(); fc['absolute_percentage_error']=safe_divide(fc.absolute_error_mw,fc.generation_mw.abs().replace(0,np.nan)); fc['forecast_alert']=fc.absolute_percentage_error>=CFG['forecast_error_alert_pct']; save(fc,GOLD,'fact_generation_forecast_accuracy'); fcm=fc.groupby(['site_id','model_version'],as_index=False).agg(forecast_count=('forecast_id','count'),mae_mw=('absolute_error_mw','mean'),mape=('absolute_percentage_error','mean'),alert_count=('forecast_alert','sum')); save(fcm,GOLD,'mart_forecast_accuracy')
    outs=s['outages'][s['outages'].site_id.isin(s['sites'].site_id)&s['outages'].asset_id.isin(s['assets'].asset_id)].copy().merge(s['sites'][['site_id','region','grid_zone']],on='site_id',how='left'); outs['major_outage_flag']=outs.customers_affected>=CFG['outage_major_customer_threshold']; save(outs,GOLD,'fact_outages'); rel=outs.groupby(['region','grid_zone'],as_index=False).agg(outage_count=('outage_id','count'),forced_outage_count=('outage_type',lambda x:int((x=='Forced').sum())),major_outage_count=('major_outage_flag','sum'),customer_interruptions=('customers_affected','sum'),customer_interruption_hours=('duration_hours',lambda x:float(x.fillna(0).sum())),energy_not_served_mwh=('estimated_energy_not_served_mwh','sum'),avg_duration_hours=('duration_hours','mean')); rel['saidi_proxy']=safe_divide(rel.customer_interruption_hours,rel.customer_interruptions); rel['saifi_proxy']=safe_divide(rel.outage_count,rel.customer_interruptions); save(rel,GOLD,'mart_grid_reliability')
    wo=s['work_orders'][s['work_orders'].asset_id.isin(s['assets'].asset_id)].copy(); wo['completion_days']=(pd.to_datetime(wo.completed_date,errors='coerce')-pd.to_datetime(wo.created_date,errors='coerce')).dt.days; save(wo,GOLD,'fact_work_orders'); maint=wo.groupby(['asset_id','maintenance_type','priority'],as_index=False).agg(work_order_count=('work_order_id','count'),completed_count=('status',lambda x:int((x=='Completed').sum())),avg_completion_days=('completion_days','mean'),labor_hours=('labor_hours','sum'),parts_cost=('parts_cost','sum')); save(maint,GOLD,'mart_maintenance_performance')
    dr=s['demand_response_events'].copy(); dr['achievement_pct']=safe_divide(dr.actual_reduction_mw,dr.target_reduction_mw); dr['target_met_flag']=dr.actual_reduction_mw>=dr.target_reduction_mw; save(dr,GOLD,'fact_demand_response_events'); save(dr.groupby('region',as_index=False).agg(event_count=('event_id','count'),target_reduction_mw=('target_reduction_mw','sum'),actual_reduction_mw=('actual_reduction_mw','sum'),target_met_count=('target_met_flag','sum'),avg_achievement_pct=('achievement_pct','mean')),GOLD,'mart_demand_response_performance')
    bills=s['bills'][s['bills'].customer_id.isin(s['customers'].customer_id)&s['bills'].total_amount.notna()].copy(); pays=s['payments'][s['payments'].bill_id.isin(bills.bill_id)&s['payments'].payment_amount.notna()&s['payments'].payment_status.eq('Posted')]; ps=pays.groupby('bill_id',as_index=False).agg(total_paid=('payment_amount','sum'),last_payment_date=('payment_date','max'),payment_count=('payment_id','count')); ar=bills.merge(ps,on='bill_id',how='left').fillna({'total_paid':0,'payment_count':0}); ar['open_amount']=ar.total_amount-ar.total_paid; asof=pd.Timestamp(CFG['past_due_as_of_date']); ar['days_past_due']=(asof-pd.to_datetime(ar.due_date,errors='coerce')).dt.days; ar['past_due_flag']=(ar.open_amount>0)&(ar.days_past_due>0); ar=ar.merge(s['customers'][['customer_id','segment','region','credit_class','autopay_flag']],on='customer_id',how='left'); save(ar,GOLD,'accounts_receivable_aging'); save(ar.groupby(['billing_month','region','segment'],as_index=False).agg(bill_count=('bill_id','count'),billed_amount=('total_amount','sum'),paid_amount=('total_paid','sum'),open_amount=('open_amount','sum'),past_due_amount=('open_amount',lambda x:float(x[ar.loc[x.index,'past_due_flag']].sum()))),GOLD,'mart_revenue_collection')
    cusage=valid_mr.groupby('customer_id',as_index=False).agg(consumption_kwh=('adjusted_kwh','sum'),peak_demand_kw=('kw_demand','max'),reading_count=('reading_id','count')); cbill=ar.groupby('customer_id',as_index=False).agg(billed_amount=('total_amount','sum'),paid_amount=('total_paid','sum'),open_amount=('open_amount','sum'),past_due_bill_count=('past_due_flag','sum')); c360=s['customers'].merge(cusage,on='customer_id',how='left').merge(cbill,on='customer_id',how='left').fillna({'consumption_kwh':0,'peak_demand_kw':0,'reading_count':0,'billed_amount':0,'paid_amount':0,'open_amount':0,'past_due_bill_count':0}); c360['collection_rate']=safe_divide(c360.paid_amount,c360.billed_amount); c360['risk_score']=c360.past_due_bill_count*10+np.where(c360.credit_class.isin(['C','D']),15,0)+np.where(c360.autopay_flag==False,5,0); save(c360,GOLD,'mart_customer_360')
    load=valid_mr.merge(s['sites'][['site_id','region','grid_zone']],on='site_id',how='left').groupby(['reading_date','grid_zone'],as_index=False).agg(load_mwh=('adjusted_kwh',lambda x:x.sum()/1000)); supply=gen.groupby(['reading_date','grid_zone'],as_index=False).agg(generation_mwh=('net_generation_mw','sum')); balance=load.merge(supply,on=['reading_date','grid_zone'],how='outer').fillna(0); balance['net_supply_gap_mwh']=balance.generation_mwh-balance.load_mwh; save(balance,GOLD,'mart_grid_supply_demand_balance')
    market=s['energy_market_prices']; mk=market.assign(reading_date=market.market_ts.dt.date.astype('string')).groupby(['reading_date','grid_zone'],as_index=False).agg(avg_real_time_price_mwh=('real_time_price_mwh','mean'),max_real_time_price_mwh=('real_time_price_mwh','max'),avg_congestion_price_mwh=('congestion_price_mwh','mean')); save(balance.merge(mk,on=['reading_date','grid_zone'],how='left'),GOLD,'mart_grid_market_position')
    save(valid_at[valid_at.anomaly_flag],GOLD,'exception_asset_telemetry_anomalies'); save(outs[outs.major_outage_flag],GOLD,'exception_major_outages'); save(fc[fc.forecast_alert.fillna(False)],GOLD,'exception_forecast_misses'); save(ar[ar.past_due_flag],GOLD,'exception_past_due_accounts'); save(mr[mr.quality_flag.isin(['MISSING','ESTIMATED'])],GOLD,'exception_meter_quality')
    dq=[]
    for n,df in raw.items(): dq.append({'check_name':f'{n}_raw_to_silver_delta','table_name':n,'raw_count':len(df),'silver_count':len(s[n]),'issue_count':len(df)-len(s[n]),'severity':'info'})
    for n,cnt in qc.items(): dq.append({'check_name':n,'table_name':n.split('_')[0],'raw_count':None,'silver_count':None,'issue_count':cnt,'severity':'warning' if cnt else 'pass'})
    save(pd.DataFrame(dq),REPORT,'data_quality_report'); save(pd.DataFrame([{'pipeline_name':CFG['project_name'],'run_timestamp_utc':pd.Timestamp.utcnow().isoformat(),'raw_file_count':len(raw),'raw_total_rows':sum(map(len,raw.values())),'silver_total_rows':sum(map(len,s.values())),'quarantine_total_rows':sum(qc.values()),'gold_table_count':len(list(GOLD.glob('*.csv'))),'status':'SUCCESS'}]),REPORT,'pipeline_audit_log')
    (META/'run_watermarks.json').write_text(json.dumps({'last_successful_run_utc':pd.Timestamp.utcnow().isoformat(),'meter_reading_watermark':str(s['meter_readings'].reading_ts.max()),'asset_telemetry_watermark':str(s['asset_telemetry'].reading_ts.max()),'generation_watermark':str(s['generation_readings'].reading_ts.max()),'status':'SUCCESS'},indent=2),encoding='utf-8')
    print('Smart Grid ETL complete.')
if __name__=='__main__': main()
